### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Fale** [jamesread/orgviz#10]
**Describe the bug**
I do not see any license in this repository.

**To Reproduce**
1. Check that there is no "LICENSE" file nor any similar files

**Expected behavior**
A license file to be present.

**Comment by jamesread** [comment]
Good point! Just for the sake of GitHub comments, I wanted to say that you and I discussed this quickly, and thought AGPL best reflects what we'd want. 

So, commit 8bb94ac11646c93059dd64faf95397a6c0b5d820 fixes this! :-)
